Repository girlscript/Girscript-Community-Website, pull requests merged in 2021-03, with the labels that each got.

#21 Created feature request template for issues
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: gssoc21, level0

#20 Created bug report template for issues
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: gssoc21, level0

#23 Fixes issue #15 : Added Dynamic Contributors Section
  README.md
Labels: Level0, gssoc21

#24 added Basic React Structure
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/Footer.js
  client/src/components/Navbar.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/yarn.lock
  package-lock.json
  package.json
Labels: Level1, gssoc21

#25 Improvement in Readme files
  Assets/Picture1.png
  Assets/Picture2.png
  Assets/Picture3.png
  Assets/Picture4.png
  Assets/Picture5.png
  Assets/img1.png
  Assets/img2.png
  README.md
  contribute.md
Labels: Level1, gssoc21

#32 Home Page New Idea
  Assets/homepage/jhasuraj/README.md
  Assets/homepage/jhasuraj/home.jpg
Labels: Level1, gssoc21

#38 home page design added
  Assets/homepage/vedika/homepage.png
Labels: Level1, gssoc21, ui

#40 Designing About Us Component
  .DS_Store
  Assets/.DS_Store
  Assets/aboutpage/.DS_Store
  Assets/aboutpage/Simran Bhardwaj/.DS_Store
  Assets/aboutpage/Simran Bhardwaj/Animate design 2.png
  Assets/aboutpage/Simran Bhardwaj/Design 1.png
  Assets/aboutpage/Simran Bhardwaj/Design working.mov
  Assets/homepage/.DS_Store
Labels: Level1, gssoc21

#44 fix link issue in the contents section in the readme
  README.md
Labels: Level0, gssoc21

#49 footer design added
  .DS_Store
  assets/.DS_Store
  assets/footer/vedika agarwal/footer.png
Labels: Level1, gssoc21

#64 mission and vision page added
  .gitignore
  frontend/src/App.js
  frontend/src/Components/Mission/dummy.js
  frontend/src/Components/Mission/mission.js
  frontend/src/Components/Mission/mission.module.css
  frontend/src/Components/Readme.md
Labels: Level3, gssoc21

#66 Testimonial Component
  .DS_Store
  frontend/package-lock.json
  frontend/src/Components/Testimonial/Card.js
  frontend/src/Components/Testimonial/Cardtemplate.js
  frontend/src/Components/Testimonial/Testimonial.css
  frontend/src/Components/Testimonial/Testimonial.js
  frontend/src/Pages/Homepage.js
  frontend/src/Test_data/Testimonial.js
  frontend/src/images/andrea.png
  frontend/src/images/bg.png
  frontend/src/images/ocomma.png
  frontend/src/images/scomma.png
Labels: Level3, gssoc21

#71 readme of frontend update
  .DS_Store
  README.md
  frontend/README.md
Labels: Level1, gssoc21

#72 testimonial modified
  frontend/src/Components/Testimonial/Testimonial.css
Labels: Level2, gssoc21

#68 added about-us section
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Common/About.js
  frontend/src/Components/Common/Common.js
  frontend/src/Components/Common/Join.js
  frontend/src/Components/Common/Newsletter.js
  frontend/src/Pages/Homepage.js
  frontend/src/index.js
Labels: Level2, gssoc21
