Repository girlscript/Girscript-Community-Website, pull requests merged in 2021-04, with the labels that each got.

#80 footer added
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/Components/Footer/footer.js
  frontend/src/Components/Footer/footer.module.css
  frontend/src/images/GsLogo_White.png
Labels: Level2, gssoc21

#79 added navabr
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Navbar/GS_logo_black(1).png
  frontend/src/Components/Navbar/Navbar.js
  frontend/src/Components/Navbar/navbar.css
  frontend/src/Pages/Homepage.js
  frontend/src/index.js
Labels: Level2, gssoc21

#76 Scroll Top
  frontend/src/Components/ScrollTop/ScrollTop.js
  frontend/src/Components/ScrollTop/scrollTop.module.css
  frontend/src/Pages/Homepage.js
Labels: Level2, gssoc21

#88 Navbar hamburger fixed
  .DS_Store
  frontend/.env
  frontend/package.json
  frontend/src/App.js
  frontend/src/Components/Navbar/NavComp.js
  frontend/src/Components/Navbar/Navbar.js
  frontend/src/Components/Navbar/navbar.css
  frontend/src/Pages/Homepage.js
  frontend/src/images/login_bg.png
  frontend/src/images/loginbg.png
  frontend/yarn.lock
Labels: Frontend, Level2

#91 Social media links added
  frontend/src/Components/Footer/footer.js
Labels: Level1, gssoc21

#89 Added our-community and our-impact section
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/Components/ourCommunity/ourCommunity.css
  frontend/src/Components/ourCommunity/ourCommunity.js
  frontend/src/Components/ourImpact/ourImpact.css
  frontend/src/Components/ourImpact/ourImpact.js
  frontend/src/Pages/Homepage.js
  frontend/src/Test_data/ourImpactPiChartData.js
Labels: Level3, gssoc21
